admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

Products:
    resource: "@ProductsBundle/Controller/"
    type:     annotation
    prefix:   /products

app:
    resource: '@AppBundle/Controller/'
    type: annotation
