admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

Glass:
    resource: "@GlassBundle/Controller/"
    type:     annotation
    prefix:   /Glass

app:
    resource: '@AppBundle/Controller/'
    type: annotation
