user_user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation

cart:
    resource: "@CartBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

Glass:
    resource: "@GlassBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout
