<?php

namespace ProductsBundle\Repository;

/**
 * GlassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlassRepository extends \Doctrine\ORM\EntityRepository
{
}
